### PR TITLE
Compass button fix

### PR DESCRIPTION
**Pull request by rwrx**
CompassView constructor change to public.

### CODE REVIEW

**Comment by ecgreb** [comment]
This pull request still includes several `*.orig` files from conflicts in the rebase. These should be removed.

Also the history still includes a number of commits that could be removed with a clean rebase against master but this is less of an issue as they can be squashed into a single commit when the pull request is merged.

**Comment by rwrx** [comment]
Ok, but I see that you have added that "public" to CompassView constructor in #259 so this pull request could be closed in favor of that pull request.

**Comment by ecgreb** [comment]
Yes that that is true I did that so I could test the sample apps. Feel free to close this one if you would prefer.

**Comment by rwrx** [comment]
Ok. Closing.

**Pull request closed without merging**
