### PR TITLE
Project dependencies

### PR DESCRIPTION
**Pull request by ecgreb**
### Overview

Replace core module external AAR dependency with local project dependency

### Proposed Changes

Also upgrades Android Gradle plugin to version 2.2.3

### CODE REVIEW

**Comment by sarahlensing** [comment]
When I install a verson of this to my local `.m2`, pull the branch of EM you posted which upgrades to ok3, refresh its dependencies, add `mavenLocal()` to the `build.gradle`, I am seeing this error:

```
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_prodDebugApkCopy'.
   > Could not find android:core:0.0.1-SNAPSHOT.
     Required by:
         eraser-map:app:0.13.2-SNAPSHOT > com.mapzen:mapzen-android-sdk:1.3.0-SNAPSHOT

* Try:
Run with --info or --debug option to get more log output.
```

Are you able to reproduce?

If so, maybe we try explicitly declaring the core dependencies in dependent modules like you mentioned?

**Comment by ecgreb** [comment]
```
> Could not find android:core:0.0.1-SNAPSHOT
```

I am not able to reproduce locally. This line suggests EM is trying to include an old snapshot of the SDK that still had the old dependency config. Did you try building with `--refresh-dependencies` or and/or deleting `~/.gradle/caches`?

**Comment by ecgreb** [comment]
After removing the folder `~/.gradle/caches` locally and rebuilding with `--refresh-dependencies` I encountered a similar error when trying to include the SDK in Eraser Map.

```
$ ./gradlew clean installDevDebug --refresh-dependencies
Download https://mint.splunk.com/gradle/com/splunk/mint/mint/4.2.1/mint-4.2.1.pom

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_prodDebugApkCopy'.
   > Could not find mapzen-android-sdk:core:unspecified.
     Required by:
         eraser-map:app:0.13.2-SNAPSHOT > com.mapzen:mapzen-android-sdk:1.3.0-SNAPSHOT

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

However instead of `android:core:0.0.1-SNAPSHOT` I am seeing `mapzen-android-sdk:core:unspecified`.

Checking the `pom.xml` that gets deployed to the local maven repo it is trying to transitively include the `core` project dependency which is obviously going to fail.

```
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.mapzen</groupId>
  <artifactId>mapzen-android-sdk</artifactId>
  <version>1.3.0-SNAPSHOT</version>
  <packaging>aar</packaging>
  <dependencies>
    <dependency>
      <groupId>mapzen-android-sdk</groupId>
      <artifactId>core</artifactId>
      <version>unspecified</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.mapzen</groupId>
      <artifactId>on-the-road</artifactId>
      <version>1.2.0-SNAPSHOT</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <artifactId>converter-gson</artifactId>
          <groupId>com.squareup.retrofit2</groupId>
        </exclusion>
      </exclusions>
    </dependency>
  </dependencies>
</project>
```

**Comment by ecgreb** [comment]
Perhaps what we are trying to do (bundle a project dependency in with the final SDK AAR) is just not possible with Gradle/Maven and we need to stick with publishing the core module as its own AAR.

**Comment by ecgreb** [comment]
After further reading and testing I don't believe it is possible to use a local project dependency on the `core` module when deploying an AAR to Maven Central as the generated `pom.xml` will never be able to resolve the transitive dependency.

Closing in favor of https://github.com/mapzen/android/pull/267 which adds custom gradle tasks to the root `build.gradle` file to ensure the `core` module is recompiled and installed to the local maven repo when building and installing the SDK, Places API, or demo applications.

**Pull request closed without merging**
