### PR TITLE
New demo app launcher icon and colors

### PR DESCRIPTION
**Pull request by ecgreb**
### Overview

Updates demo app launcher icons and colors

### Proposed Changes

screenshot_20170323-222243

screenshot_20170323-222313

screenshot_20170323-222618

screenshot_20170323-222926

### CODE REVIEW

**Comment by souperneon** [comment]
Everything looks great. I'm sorry, but I am changing my mind about the logo and icon.
Purple on white looks much better! Also, maybe rounded edge square? (Can't believe I just said that!) 
Also, a different places logo?

[Archive.zip](https://github.com/mapzen/android/files/868379/Archive.zip)

**Comment by sarahlensing** [comment]
screenshot_20170331-151837

@souperneon I grabbed the new icons/logos from your archive. How do they look to you?

**Comment by souperneon** [comment]
These look good! What do you think @ecgreb @sarahlensing?

**Comment by ecgreb** [comment]
Agree it does look good! I just want to double check how the new icon looks on my device which has a white background in the app drawer. Will post images shortly.

Also @souperneon did you want to use rounded corners or stick with them squared?

**Comment by souperneon** [comment]
If you can post a screenshot with the rounded? That's the new world ;)

**Comment by ecgreb** [comment]
@souperneon I would be happy to but the zip file [attached here](https://github.com/mapzen/android/pull/345#issuecomment-289057041) still has square corners!

**Comment by souperneon** [comment]
Oh, this is not like iOS where the corners automatically round? ;)

**Comment by ecgreb** [comment]
🤖 📵

**Comment by ecgreb** [comment]
@souperneon any update on the rounded mapzen icon?

**Comment by sarahlensing** [comment]
@souperneon how does this look?

screenshot_20170504-151220

**Comment by souperneon** [comment]
Beautiful! 👍

**Pull request merged**
